//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Store.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSale
    {
        public int saleId { get; set; }
        public Nullable<int> saleProduct { get; set; }
        public Nullable<int> saleEmployee { get; set; }
        public Nullable<int> saleCustomer { get; set; }
        public Nullable<decimal> saleAmount { get; set; }
        public Nullable<System.DateTime> saleDate { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblProduct tblProduct { get; set; }
    }
}
